webtalk_init -webtalk_dir D:/UCT 2023/EEE4120F High Performance Embedded Systems/YODA/ReadImage/YODA_module_read - BRAM working - Copy/YODA_module_read.sim/sim_1/behav/xsim/xsim.dir/read_Testbench_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue May 16 15:05:21 2023" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "2f64402d-d564-4469-bc6c-927321f3c3da" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "70fe761d54d94fca85fae8e799a57879" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "242" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2803 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "38.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.00_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "9476_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1370185954 -regid "" -xml D:/UCT 2023/EEE4120F High Performance Embedded Systems/YODA/ReadImage/YODA_module_read - BRAM working - Copy/YODA_module_read.sim/sim_1/behav/xsim/xsim.dir/read_Testbench_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/UCT 2023/EEE4120F High Performance Embedded Systems/YODA/ReadImage/YODA_module_read - BRAM working - Copy/YODA_module_read.sim/sim_1/behav/xsim/xsim.dir/read_Testbench_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/UCT 2023/EEE4120F High Performance Embedded Systems/YODA/ReadImage/YODA_module_read - BRAM working - Copy/YODA_module_read.sim/sim_1/behav/xsim/xsim.dir/read_Testbench_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
